### ISSUE TITLE
RenderFlex overflow error

### ISSUE THREAD

**Issue by shubhangi-singh21** [shubhangi-singh21/Check-It#1]
tried solving by:

- SingleChildScrollView

- Expanded

not working :/

**Comment by rrkas** [comment]
I am interested in solving this issue.
please assign this issue to me.

**Comment by shubhangi-singh21** [comment]
> I am interested in solving this issue.
> please assign this issue to me.

@rrkas could you just explain your method before proceeding? It would be helpful for both of us.

**Comment by rrkas** [comment]
I will try to figure out which widget is causing the overflow.
Then I'll try few combinations of widgets that helped me a lot in my past few projects to overcome this overflow condition.
Most probably the widgets I'll use:
Expanded/sizedbox/limitedbox
Container/row/column
Fittedbox

Edit:
If its related to overflow due to keyboard, I'll have to use some scrolling widgets like SingleChildScrollView or ListView

**Comment by shubhangi-singh21** [comment]
> I will try to figure out which widget is causing the overflow.
> Then I'll try few combinations of widgets that helped me a lot in my past few projects to overcome this overflow condition.
> Most probably the widgets I'll use:
> Expanded/sizedbox/limitedbox
> Container/row/column
> Fittedbox
> 
> Edit:
> If its related to overflow due to keyboard, I'll have to use some scrolling widgets like SingleChildScrollView or ListView

okay @rrkas you can go ahead👍

**Comment by rrkas** [comment]
error solved. please see pull request #2
